<?php $this->printGoBackUrl($this->url(array('action'=>'index'))); ?>

<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Data Sistem Pendorong Motor Listrik (Diesel Generator)</h2>
	<div class="toggle_container">
		<div class="block">
			<?php 
            $this->form->setAction($this->url());
            $this->form->getElement('id_kapal')->setValue( $this->id );
			echo $this->form;
			?>
		</div>
	</div>
</div>
