<div class="flat_area grid_16">
	<h2>Data Pokok KRI</h2>
    <p>
        <a href="<?php echo $this->url(array('action'=>'add')); ?>" class="roundall_grey add_icon">
            <span class="ml22">Data KRI Baru</span>
        </a>
    </p>
	<div class="block">
		<table id="table-dtables" class="display">
			<thead>
			<tr>
				<th width="20%">Nama KRI</th>
				<th width="10%">Singkatan</th>
				<th width="10%">No. Lamb</th>
				<th width="10%">Jenis</th>
				<th width="10%">Type</th>
				<th width="10%">Negara Asal</th>
				<th width="10%"></th>
			</tr>
			</thead>
		</table>
	</div>
</div>

<script type="text/javascript">
	<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
	$(function(){
		var oTable = $('#table-dtables').dataTable({
			"iDisplayLength": 30,
	 		"aLengthMenu" : [ 15, 30, 50, 100 ],
			"bJQueryUI": true,
			"sScrollX": "",
			"bSortClasses": false,
			"aaSorting": [[0,'asc']],
			"bAutoWidth": true,
			"bInfo": true,
			"bFilter": true,
			"sScrollY": "100%",
			"sScrollX": "100%",
			"bScrollCollapse": true,
			"sPaginationType": "full_numbers",
			"bProcessing" : true,
			"bServerSide" : true,
			"sAjaxSource" : '<?php echo $this->url(); ?>',
			"fnServerData" : function(sSource, aoData, fnCallback) {
				jQuery.getJSON(sSource, aoData, function(json) {
					fnCallback(json);
				});
			},
			'aoColumns' : [
				null,
				null,
				null,
				null,
				null,
				null,
				{bSortable: false, bSearchable: false}
			]
		});

		new Filterer(oTable);

		$('#table-dtables_filter').css('width', '360px');
	});
</script>