<?php $this->printGoBackUrl($this->url(array('action'=>'index', 'id'=>null))); ?>

<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Ubah Simbol Taktis</h2>
	<div class="toggle_container">
		<div class="block">
			<img src="<?php echo $this->baseUrl().$this->crud->get('filepath'); ?>">
			<?php 
			$this->form->setAction($this->url());
			echo $this->form;
			?>
		</div>
	</div>
</div>
