<div class="flat_area grid_16">
	<h2>Data CB Logistik</h2>
    <div class="map-top-nav">
        <a href="<?php echo $this->url(array('action'=>'add')); ?>" class="roundall_grey add_icon float-left">
            <span class="ml22">CB Logistik</span>
        </a>
    </div>

	<div class="toggle_container" style="display: block; ">
		<div class="block">
			<table id="table-dtables" class="display">
				<thead>
					<tr>
						<th>Nomor CB</th>
						<th>Waktu Pembuatan</th>
						<th>Skenario Latihan</th>
						<th width="15%"></th>
					</tr>
				</thead>
			</table>
		</div>
	</div>
</div>

<script type="text/javascript">
<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
$(function(){
    var oTable = $('#table-dtables').dataTable({
        "bJQueryUI": true,
        "sScrollX": "",
        "bSortClasses": false,
        "aaSorting": [[0,'asc']],
        "bAutoWidth": true,
        "bInfo": true,
//        "bFilter": false,
        "sScrollY": "100%",
        "sScrollX": "100%",
        "bScrollCollapse": true,
        "sPaginationType": "full_numbers",
        "bProcessing" : true,
        "bServerSide" : true,
        "sAjaxSource" : '<?php echo $this->url(array('action'=>'dataapi')); ?>',
        "fnServerData" : function(sSource, aoData, fnCallback) {
            // @optional filter category content
            jQuery.getJSON(sSource, aoData, function(json) {
                fnCallback(json);
            });
        },
		'aoColumns' : [null,{bSearchable: false},null,{bSortable: false}]
    });
	new Filterer(oTable);
});
</script>