<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">CB Logistik</h2>
	<div class="toggle_container">
		<div class="block">
			<?php foreach($this->obj->toViewArray() as $key => $value) : ?>
            <label><?php echo $key; ?>:</label>
            <label style="font-weight: normal;"><?php echo $value; ?></label>
            <br />
            <?php endforeach; ?>
		</div>
	</div>
</div>

<div class="flat_area grid_16">
	<p><a href="<?php echo $this->url(array('action'=>'index', 'id'=>null)); ?>">Kembali</a></p>
</div>