<div class="map-top-nav">
    <a href="<?php echo $this->url(array('action'=>'list')); ?>" class="roundall_grey back_icon float-right">
        <span class="ml22">Kembali</span>
    </a>
</div>

<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Ubah Rumahsakit Pendukung : <?php echo $this->nocb; ?></h2>
	<div class="toggle_container">
		<div class="block">
			<?php 
			$this->form->setAction($this->url());
			echo $this->form;
			?>
		</div>
	</div>
</div>
<div class="box grid_8 round_all">
    <h2 class="box_head grad_colour">Preview Map</h2>
    <div id="map"></div>
</div>
<?php echo $this->render('cbl-rumahsakit/cms-script.phtml');?>
<script type="text/javascript">
    getData('<?php echo $this->id;?>');
</script>