<div class="flat_area grid_16">
	<a href="<?php echo $this->url(array('action'=>'list', 'id'=>null)); ?>" class="roundall_grey back_icon float-right">
		<span class="ml22">Kembali</span>
	</a>
</div>

<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Ubah Materi Penilaian Produk Naskah</h2>
	<div class="toggle_container">
		<div class="block">
			<?php 
			$this->form->setAction($this->url());
            foreach($this->parents as $parent):
                $this->form->getElement('parent')->addMultiOption($parent['id'], $parent['materi']);
            endforeach;
			echo $this->form;
			?>
		</div>
	</div>
</div>
