<script type="text/javascript">
    var idTeam = '<?php echo $this->idTeam; ?>';
</script>
<div class="flat_area grid_16">

    <!-- box header label -->
    <h2>Daftar Tim</h2>
    <div class="map-top-nav">
        <p>
            <label for="team_name">Nama Tim</label>
            <input type="text" id="team_name" value="<?php echo $this->data['team_name']; ?>" /></br>
            <label for="sken">Skenario</label>
            <select id="sken">
                <?php foreach($this->allSken as $sken): ?>
                <?php if($sken['id'] == $this->data['id_skenario']): ?>
                    <option value="<?php echo $sken['id']; ?>" selected="selected"><?php echo $sken['nomor']; ?></option>
                    <?php else: ?>
                    <option value="<?php echo $sken['id']; ?>"><?php echo $sken['nomor']; ?></option>
                    <?php endif; ?>
                <?php endforeach; ?>
            </select>
        </p>
    </div>

    <!-- toggle button -->
    <a href="#" class="toggle">&nbsp;</a>

    <!-- container -->
    <div class="toggle_container" style="display: block; ">

        <div class="block">
            <table id="table_team" class="display">
                <thead>
                <tr>
                    <th></th>
                    <th>Username</th>
                    <th>Jabatan</th>
                    <th>Nama</th>
                </tr>
                </thead>
            </table>
            <form action="<?php echo $this->baseUrl('management/team/updateteam');?>" method="post">
                <input type="hidden" name="id_siswa" id="id_siswa" />
                <input type="hidden" name="id_skenario" id="id_sken" />
                <input type="hidden" name="tim_name" id="nama_tim" />
                <input type="hidden" name="id_team" id="id_tim" value="<?php echo $this->data['id'];?>" />
                <input type="hidden" name="self" value="other"  />
                <input type="hidden" name="status" id="status">
                <button class="roundall_grey">
                    <span>Simpan</span>
                </button>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    var checkedArr = [];
    var ceklis = [];

    $(function(){
        var oTable = $('#table_team').dataTable( {
            "bJQueryUI": true,
            "sScrollX": "",
            "bSortClasses": false,
            "aaSorting": [[0,'asc']],
            "bAutoWidth": true,
            "bInfo": true,
            "aoColumns":[
                null,
                null,
                null,
                null
            ],
            "sScrollY": "100%",
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "sPaginationType": "full_numbers",
            "bProcessing" : true,
            "bServerSide" : true,
            "sAjaxSource" : baseUrl + '/management/team/dataapiedit',
            "fnServerData" : function(sSource, aoData, fnCallback)
            {
                //filter category content
//                if(jQuery('#feed-filter').length)
//                {
//                    filter = jQuery('#feed-filter').val();
//
//                    aoData.push({
//                        "name": "feed-filter",
//                        "value":  filter
//                    });
//                }

                aoData.push({
                    "name": "idTeam",
                    "value": idTeam
                });

                jQuery.getJSON(sSource, aoData, function(json) {
                    //if(aaData != 'undefined')
                    //{
                    fnCallback(json)
                    //}
                });

                $('.custom-rows').parent().css('vertical-align','middle');
            }

        })//.makeEditable()

        $('table').delegate(':checkbox', 'click', function()
        {
            if($(this).is(':checked'))
            {
                checkedArr.push($(this).val());
                ceklis.push('T');
            }
            else
            {
                checkedArr.push($(this).val());
                ceklis.push('F');
            }
            $('#id_siswa').val(checkedArr.join(','));
            $('#status').val(ceklis.join(','));
        });
    });

    $('#team_name').change(function(){
        document.getElementById('nama_tim').value = this.value;
    });

    $('#sken').change(function(){
        document.getElementById('id_sken').value = this.value;
    });

//    function selectedValue(selectObj)
//    {
//        var idx = selectObj.selectedIndex;
//        var which = selectObj.options[idx].value;
//        document.getElementById('filter_value').value = which;
//    }
</script>