<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Ubah Pergerakan Sendiri</h2>
	<div class="toggle_container">
		<div class="block">
			<?php 
			$this->form->setAction($this->url());
			echo $this->form;
			?>
		</div>
	</div>
</div>

<div class="flat_area grid_16">
	<p><a href="<?php echo $this->url(array('action'=>'pergerakan', 'id'=>null)); ?>">Kembali</a></p>
</div>

<script>
$(function() {
	$('input[name="tanggal"]').datepicker({
		dateFormat: 'yy-mm-dd'
	});
	$('input[name="waktu"]').timepicker({
		showSecond: true,
		timeFormat: 'hh:mm:ss'
	});
});
</script>