<div class="flat_area grid_16">
	<h2>Daftar Aspek Penilaian</h2>
    <div class="map-top-nav">
		<a class="roundall_grey add_icon mr3 float-left" href="<?php echo $this->url(array('action'=>'add')); ?>">
            <span class="ml22">Aspek Penilaian Baru</span>
        </a>
	</div>
	<div class="block">
		<table class="display simple-table">
			<thead>
				<tr>
					<th>Aspek</th>
					<th>Nilai Maksimum</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<?php if ($this->items) foreach ($this->items as $i => $item) : ?>
					<tr class="<?php echo ($i%2) ? 'even' : 'odd'; ?>">
						<td><?php echo $item['aspek_nilai']; ?></td>
						<td><?php echo $item['nilai_maks']; ?></td>
						<td>
							<a href="<?php echo $this->url(array('action'=>'edit', 'id'=>$item['id'])); ?>">Ubah</a> |
							<a href="<?php echo $this->url(array('action'=>'del', 'id'=>$item['id'])); ?>" onclick="return confirm('Anda yakin?')">Hapus</a>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
    <div class="block grid_8" style="margin-top: 20px; margin-bottom: 20px;">
        <div style="float: left; margin-top: 5px;margin-right: 20px;">
            <label for="copy-id" style="float: left; margin-top: 5px;">Copy Dari Team: </label>
            <select id="copy-id">
                <option value="">Pilih</option>
                <?php foreach($this->team as $team): ?>
                    <option value="<?php echo $team['id'];?>"><?php echo $team['team_name'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <a id="copy-link" style="clear: none; margin: 5px; margin-left: 0;" class="skin_colour send_right on_dark text_only has_text" href="javascript:void(0)">
            <span>Copy Aspek</span>
        </a>
    </div>
</div>


<script type="text/javascript">
    $('#copy-link').click(function(){
        if($('#copy-id').val() != '') {
            var r=confirm("Hapus semua aspek dan copy dari team lain ?");
            if (r==true)
            {
                window.open('<?php echo $this->url(array('action'=>'copy')); ?>' + '/copyid/' + $('#copy-id').val() ,'_self');
            }
            else
            {
                return false;
            }
        } else {
            alert('Pilih team yang akan di-copy terlebih dahulu!')
        }
    });
</script>

