
<?php $this->headLink()->appendStylesheet( $this->cssUrl( 'print/preview-layout3.css' ), 'screen' )
    ->appendStylesheet( $this->cssUrl( 'print/print-layout3.css' ),'print' )
;
?>

<?php $i = 1; ?>
<?php if($this->aspek): ?>
    <?php foreach($this->aspek as $pel): ?>
        <div class="halaman" style="width: 19cm; position: relative; height:24cm; margin-left: 10px; page-break-after:always; display: inline-block;">
            <div class="header-area">
                <div class="header">
                    MARKAS BESAR ANGKATAN LAUT<br/>
                    SEKOLAH STAF DAN KOMANDO
                </div>
                <div class="dateday-area">
                    <span>Hari ................... , </span>
                    <span>Tgl ....................</span>
                </div>
            </div>
            <div style="width: 100%; text-align: center; clear: both;">
                <h3 style="margin-bottom: 0;">PENILAIAN PAPARAN NASKAH ..............................................................................................................</h3>
                <h3 style="margin-top: 0;margin-bottom: 0;">TAHUN ........... - ...........</h3>
                <h3 style="margin-top: 0;"><?php echo strtoupper($this->scenario); ?></h3>
            </div>
            <div>
                <h3 style="margin-left: 50px;">
                    <?php $kogasCount = count($this->kogas); ?>
                    <?php foreach($this->kogas as $indexKogas => $kogas){ ?>
                        <?php echo $kogas['nama']; ?>
                        <?php if($indexKogas != ($kogasCount - 1)) echo ' // '; ?>
                    <?php } ?>
                </h3>
            </div>
            <div style="position: relative;">
                <table class="btable">
                    <thead>
                    <tr>
                        <th rowspan="2" width="5%">No.</th>
                        <th rowspan="2" width="40%">Aspek Yang Dinilai</th>
                        <th colspan="3">Nilai</th>
                        <th rowspan="2" width="20%">Keterangan</th>
                    </tr>
                    <tr>
                        <th>Nilai Mak</th>
                        <th>Nilai</th>
                        <th>Jumlah Nilai</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php if(!empty($pel)): ?>
                            <?php foreach($pel as $indexKogas => $kogas): ?>
                                <tr class="<?php echo ($k%2) ? 'even' : 'odd'; ?>">
                                    <td rowspan="<?php echo count($pel[$indexKogas]['aspek'])+1; ?>" style="vertical-align: top; font-weight: bold;">
                                        <?php echo $indexKogas.'.'; ?>
                                    </td>
                                    <td style="border-top: none;border-bottom: none;font-weight: bold;">
                                        <?php echo strtoupper($kogas['nama']); ?>
                                    </td>
                                    <td style="border-top: none;border-bottom: none;"></td>
                                    <td style="border-top: none;border-bottom: none;"></td>
                                    <td rowspan="<?php echo count($pel[$indexKogas]['aspek'])+1; ?>" style="border-top: none;vertical-align: middle;font-size: 18px; text-align: center; font-weight: normal;">
                                        <?php echo $kogas['totalNilai']; ?>
                                    </td>
                                    <td style="border-top: none;border-bottom: none;"></td>
                                </tr>

                                <?php $j = 1; ?>
                                <?php foreach($pel[$indexKogas]['aspek'] as $index => $aspek): ?>
                                    <?php if(intval($index) != (count($pel[$indexKogas]['aspek'])-1)): ?>
                                    <tr class="<?php echo ($i%2) ? 'even' : 'odd'; ?>">
                                        <td style="border-top: none;border-bottom: none;"><?php echo '- '.$aspek['aspek_nilai']; ?></td>
                                        <td style="border-top: none;border-bottom: none; text-align: center;"><?php echo $aspek['nilai_maks']; ?></td>
                                        <td style="border-top: none;border-bottom: none;text-align: center;"><?php echo $aspek['nilai'];?></td>
                                        <td style="border-top: none;border-bottom: none;text-align: center;"><?php echo $aspek['keterangan'];?></td>
                                    </tr>
                                        <?php else: ?>
                                    <tr class="<?php echo ($i%2) ? 'even' : 'odd'; ?>">
                                        <td style="border-top: none;"><?php echo '- '.$aspek['aspek_nilai']; ?></td>
                                        <td style="border-top: none; text-align: center;"><?php echo $aspek['nilai_maks']; ?></td>
                                        <td style="border-top: none;text-align: center;"><?php echo $aspek['nilai'];?></td>
                                        <td style="border-top: none;text-align: center;"><?php echo $aspek['keterangan'];?></td>
                                    </tr>
                                    <?php endif; ?>
                                <?php $j++; endforeach; ?>


                            <?php $i++; endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <div class="ftable-wrapper" style="left: 60%; width: 40%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="3">PENILAI</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Nama</td>
                            <td>:</td>
                            <td><?php echo $this->penilai['nama'];?></td>
                        </tr>
                        <tr>
                            <td>PKT/KORPS/NRP</td>
                            <td>:</td>
                            <td><?php echo $this->penilai['pangkat'].' / - / '.$this->penilai['nrp'];?></td>
                        </tr>
                        <tr>
                            <td>Tanda Tangan</td>
                            <td>:</td>
                            <td height="50px"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <h1>Mohon maaf, anda tidak memiliki hak akses.</h1>
<?php endif;?>