<div class="flat_area grid_16">
	<h2>Role Setting</h2>
</div>
<div class="grid_16">
	<div class="box clearfix grid_5">
		<h2 class="box_head grad_colour round_top">Nama Role</h2>
		<div id="list">
			<div class="list-content">
				<ul>
					<?php foreach($this->roles as $r): ?>
					<li><span id="r-<?php echo $r->id; ?>"><?php echo $r->name; ?></span></li>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>
	</div>

	<div class="flat_area grid_11">
		<h2>Hak Akses</h2>
	</div>

	<div class="grid_11">
		<form action="<?php echo $this->url(); ?>" method="POST" class="box">
			<button class="button_colour round_all" style="position: absolute; top:-49px; right: -5px;">
				<span>Simpan</span>
			</button>
			<select id="previlages" class="multiselect" multiple="multiple" name="previlages[]">

			</select>
			<input id="id_role" name="id_role" type="hidden"/>
		</form>
	</div>


    <div class="block  grid_11 indented_button_bar clearfix" style="clear: both; float: right; margin-bottom: 20px;">
        <div style="float: right;">
            <div style="float: left; margin-top: 5px;margin-right: 20px;">
                <label for="copy-id" style="float: left; margin-top: 5px;">Copy Dari Role: </label>
                <select id="copy-id">
                    <option value="">Pilih</option>
                    <?php foreach($this->team as $team): ?>
                    <option value="<?php echo $team['id'];?>"><?php echo $team['team_name'];?></option>
                    <?php endforeach; ?>
                </select>
            </div>
            <a id="copy-link" style="clear: none; margin: 5px; margin-left: 0;" class="skin_colour send_right on_dark text_only has_text" href="javascript:void(0)">
                <span style="margin: 0 5px;">Copy Previlages</span>
            </a>
        </div>
    </div>
</div>

<style type="text/css">
	.multiselect {
		width: 100%;
		height: 308px;
	}
</style>

<script type="text/javascript">
	$(function(){
        var $globalidrp;

		$('.list-content ul li span').click(function(){
			var myarr = $(this).attr('id').split("-");
			var $idrp = myarr[1];
            $globalidrp = $idrp;

			$.ajax({
				url: '<?php echo $this->url(); ?>',
				type: "GET",
				data: {rolId : $idrp},
				success: function(data) {

					$('#previlages').html('');

					$.each($.parseJSON(data), function() {
						var $option = $('<option></option>');
						$option.val(this.id);
						$option.text(this.name);
						$option.attr('modules', this.module);
						$option.attr('controllers', this.controller);
						$option.attr('actions', this.actions);
						if(typeof this.checked != "undefined") {
							$option.attr('selected', 'selected');
						}
						$('#previlages').append($option);

					});

				}
			}).done(function() {
				$('#id_role').val($idrp);
				$('.multiselect').multiselect('destroy').multiselect({sortable : false});

				$('ul.connected-list>li').tipsy({title: function() {
					String.prototype.breakAt=function(a){return this.substr
					(0,a)+'<br>'+this.substr(a)};

					var text = 'Module : ' + this.getAttribute('modules') + '<br/>';
					text += 'Controller : ' + this.getAttribute('controllers') + '<br/>';
					text += 'Actions : ' + this.getAttribute('actions').breakAt(45);
					return text;
				},
					html: true,
					gravity: 'nw',
					offset: -10
				});

                $.ajax({
                    url: '<?php echo $this->url(array('action'=>'other-role')); ?>',
                    type: "GET",
                    data: {rolId : $idrp},
                    success: function(data) {
                        $('#copy-id').html('<option value="">Pilih</option>');
                        $.uniform.update("#copy-id");

                        $.each($.parseJSON(data), function() {
                            var $optionCopy = $('<option></option>');
                            $optionCopy.val(this.id);
                            $optionCopy.text(this.name);
                            $('#copy-id').append($optionCopy);
                        });
                    }
                });
			});
		});

        $('#copy-link').click(function(){

            if(typeof $globalidrp != "undefined") {
                if($('#copy-id').val() != '') {
                    var r=confirm("Hapus semua previlage di role ini  dan copy dari role lain ?");
                    if (r==true)
                    {
                        window.open('<?php echo $this->url(array('action'=>'copy')); ?>' + '/sourceid/' + $globalidrp + '/copyid/' + $('#copy-id').val() ,'_self');
                    }
                    else
                    {
                        return false;
                    }
                } else {
                    alert('Pilih role yang akan di-copy terlebih dahulu!')
                }

            } else {
                alert('Pilih role terlebih dahulu!')
            }


        });
	});
</script>
