<div class="flat_area grid_16">
	<h2>Daftar Radar</h2>
	<p>
		<a class="roundall_grey add_icon" href="<?php echo $this->url(array('controller'=>'radar','action'=>'add.radar')); ?>">
			<span class="ml22">Radar Baru</span>
		</a>
	</p>
	
	<div class="block">
		<table id="table-radar" class="display">
			<thead>
				<tr>
					<th width="20%">Name</th>
					<th>Elevation</th>
					<th>Type</th>
					<th>Max Range</th>
					<th>Freq</th>
					<th>Jamming Range</th>
					<th width="10%"></th>
				</tr>
			</thead>
		</table>
	</div>
</div>

<script type="text/javascript">
<?php $this->inlineScript()->appendFile($this->jsUrl( 'script.js')); ?>
$(function(){
    var oTable = $('#table-radar').dataTable({
        "bJQueryUI": true,
        "sScrollX": "",
        "bSortClasses": false,
        "aaSorting": [[0,'asc']],
        "bAutoWidth": true,
        "bInfo": true,
        "bFilter": true,
        "sScrollY": "100%",
        "sScrollX": "100%",
        "bScrollCollapse": true,
        "sPaginationType": "full_numbers",
        "bProcessing" : true,
        "bServerSide" : true,
        "sAjaxSource" : baseUrl + '/cms/radar/dataapi.radar',
        "fnServerData" : function(sSource, aoData, fnCallback) {
            // @optional filter category content
            jQuery.getJSON(sSource, aoData, function(json) {
                fnCallback(json);
            });
        },
		'aoColumns' : [
			// Name bisa disearch
			null,
			// Elevation tidak bisa disearch
			{bSearchable: false},
			// Type bisa disearch
			null,
			// Max Range, Freq, Jamming Range tidak bisa disearch
			{bSearchable: false},{bSearchable: false},{bSearchable: false},
			// tidak bisa disearch maupun disort
			{bSortable: false, bSearchable: false}]
    });//.makeEditable();
	new Filterer(oTable);
});
</script>