<?php $this->printGoBackUrl($this->url(array('action'=>'index'))); ?>

<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Import Data Fasilitas Labuh Udara</h2>
	<div class="toggle_container">
		<div class="block">
			<?php if (isset($this->announcement)) : ?>
				<div class="alert alert_green">
					<img width="24" height="24" src="<?php echo $this->imgUrl('icons/small/white/Alert%202.png'); ?>">
					<?php echo $this->announcement; ?>
				</div>
			<?php endif; ?>
			
			<?php if (count($this->importer->getErrors())) : ?>
				ERROR:
				<?php foreach ($this->importer->getErrors() as $y => $messages) : ?>
					<p>Baris <?php echo $y; ?> mengandung error
					</p>
				<?php endforeach; ?>
			<?php endif; ?>
			
			<?php echo $this->form; ?>
		</div>
	</div>
</div>
