<div class="flat_area grid_16">
    <h2>Daftar Fasilitas Labuh Udara</h2>

    <div class="map-top-nav">
        <a href="<?php echo $this->url(array('action'=>'add')); ?>" class="roundall_grey add_icon mr3 float-left">
            <span class="ml22">Labuh Udara Baru</span>
        </a>
		<a href="<?php echo $this->url(array('action'=>'import')); ?>" class="roundall_grey xl_icon mr3 float-right">
			<span class="ml22">Import Excel</span>
		</a>
    </div>

    <div class="block">
        <table id="table-dtables" class="display">
            <thead>
            <tr>
                <th>Nama Lanal</th>
                <th>Nama Item</th>
                <th>Jenis Konstruksi</th>
                <th>Luas</th>
                <th>Panjang</th>
                <th>Lebar</th>
                <th>Kemampuan</th>
                <th>Kondisi</th>
                <th>Keterangan</th>
                <th width="10%"></th>
            </tr>
            </thead>
        </table>
    </div>
</div>

<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
<script type="text/javascript">
    $(function(){
        var oTable = $('#table-dtables').dataTable({
            "bJQueryUI": true,
            "sScrollX": "",
            "bSortClasses": false,
            "aaSorting": [[0,'asc']],
            "bAutoWidth": true,
            "aoColumns":[
                null,
                null,
                null,
				{bSearchable: false},
				{bSearchable: false},
				{bSearchable: false},
                null,
                null,
                null,
                {bSortable:false}
            ],
            "bInfo": true,
//            "bFilter": false,
            "sScrollY": "100%",
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "sPaginationType": "full_numbers",
            "bProcessing" : true,
            "bServerSide" : true,
            "sAjaxSource" : '<?php echo $this->url(array('action'=>'dataapi')); ?>',
            "fnServerData" : function(sSource, aoData, fnCallback) {
                // @optional filter category content
                jQuery.getJSON(sSource, aoData, function(json) {
                    fnCallback(json);
                });
            }
        });//.makeEditable();
		new Filterer(oTable);
    });
</script>