<div class="flat_area grid_16">

	<a class="roundall_grey back_icon float-right" href="<?php echo $this->siteUrl('komunikasi'); ?>">
		<span class="ml22">Kembali</span>
	</a>

	<div class="box grid_8 round_all">
		<h2 class="box_head grad_colour">Masukkan Password</h2>
		<div class="toggle_container">
			<div class="block">
				<form action="<?php echo $this->siteUrl('komunikasi/index/validatemoderator/meetingid/' . $this->meetingID .'/role/' . $this->role ); ?>">
					<label>Password</label>
					<input type="text" name="password" class="small required">
					<button type="submit">
						<img src="<?php echo $this->imgUrl('icons/small/white/Refresh%204.png'); ?>" />
						<span>Kirim</span>
					</button>
				</form>
			</div>
		</div>
	</div>

</div>

<script type="text/javascript">

	var defaultRoomPw = <?php echo $this->defaultPassword; ?>

		$(function(){
			$('#status').change(function(){
				if($(this).val() == 'open'){
					$('#label_attendeePW').hide();
					$('#attendeePW').hide().val(defaultRoomPw);
				}else{
					$('#label_attendeePW').show();
					$('#attendeePW').show().val('');
				}
			});
		});

</script>