<script type="text/javascript">
    <?php $this->inlineScript()->captureStart(); ?>
    <?php $this->inlineScript()->appendFile( $this->jsUrl( 'script.js' ) );?>
    <?php $this->inlineScript()->captureEnd(); ?>
</script>
<style type="text/css">
    #controlToggle li {list-style: none;}
    p {width: 512px; }

        /* avoid pink tiles */
    .olImageLoadError {
        background-color: transparent !important;
    }
</style>
<script type="text/javascript">
    <?php $this->inlineScript()->captureStart(); ?>
    //    Openlayer start here
    var proxyUrl = "<?php echo $this->baseUrl('peta/proxy/?url='); ?>";
    <?php $this->inlineScript()->captureEnd(); ?>
</script>

<div class="grid_8">
    <?php echo $this->form; ?>
</div>

<div class="grid_8" style="height:463px;">
    <!-- preview rute -->
    <div class="box round_all">
        <h2 class="box_head grad_colour">Preview Rute</h2>
        <div id="map2"></div>
    </div>
</div>

<script type="text/javascript">
    var markers, size, iconMatra, offset, icon;
    $(function(){
        var wgs84 = new OpenLayers.Projection("EPSG:4326");
        var format = 'image/png';
        var map, drawControls;

        $('#map2').css('height', '400px');

        var options = {
            controls: [],
            //maxExtent: bounds,
            maxResolution: 0.0780,
            projection: wgs84,
            units: 'degrees',
            restrictedExtent: new OpenLayers.Bounds(95.115729755272, -12.012413207701, 140.70672975527, 7.4095867922987)
        };

        map = standardMap('map2','option');

        //add new marker
        markers = new OpenLayers.Layer.Markers( "Markers");
        map.addLayer(markers);

        iconMatra = baseUrl + '/images/icons/red_circle.png';

        size = new OpenLayers.Size(21,25);
        offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
        icon = new OpenLayers.Icon(iconMatra, size, offset);

        //map.addControl(new OpenLayers.Control.LayerSwitcher());
        map.addControl(new OpenLayers.Control.MousePosition());

        /* == Fitur (Control)Zoom Area + Drag Pan */
        // override NavToolbar untuk mendisable scroll
        var CustomNavToolbar = OpenLayers.Class(OpenLayers.Control.NavToolbar, {
            initialize: function(options) {
                OpenLayers.Control.Panel.prototype.initialize.apply(this, [options]);
                this.addControls([
                    new OpenLayers.Control.Navigation({'zoomWheelEnabled': false}), // disable scroll di sini
                    new OpenLayers.Control.ZoomBox()
                ]);
            }
        });

        map.events.register('click', map, function(e) {
            var lonlat = map.getLonLatFromViewPortPx(e.xy);
            //lonlatArr.push(lonlat.lon + ',' + lonlat.lat);
            //document.getElementById('point').value = lonlatArr.join('|');
            document.getElementById('longitude').value = lonlat.lon;
            document.getElementById('latitude').value = lonlat.lat;

            markers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(lonlat.lon,lonlat.lat),icon));
        });
    });
</script>