<div class="map-top-nav grid_16">
    <a href="<?php echo $this->url(array('action'=>'list')); ?>" class="roundall_grey add_icon float-left">
        <span class="ml22">Depo Pendukung</span>
    </a>

    <a href="<?php echo $this->url(array('controller'=>'cb-logistik','action'=>'detail','cbid'=>$this->cbid->getId())); ?>" class="roundall_grey back_icon float-right">
        <span class="ml22">Kembali</span>
    </a>
</div>

<div class="box grid_8 grid_16 round_all contentmap " >
    <h2 class="box_head grad_colour titlemap">
        <span>Depo Pendukung</span>
    </h2>
    <div id="map" style="top: -1px"></div>
</div>

<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
<style type="text/css">
    .list-pendukung{
        width: 150px;
    }
    .list-pendukung tr th{
        border: 1px solid;
        background: blue;
        color: #fff;
        padding: 5px;
    }
    .list-pendukung tr td{
        padding: 5px;
    }
</style>
<script>

    // global map object
    var map,titik_referensi;
    var rsPendukung;
    // layers dan geourl ada di script.js

    $(function(){
        $('#map').css('height', '500px');
        map = standardMap('map');

        // Marker Pangkalan Pendukung
        var ll, popupContentHTML;
        var AutoSizeFramedCloud = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
            'autoSize': true
        });
        //-- icon --
        var size = new OpenLayers.Size(18,18); // size icon
        var offset = new OpenLayers.Pixel(-(size.w/2), -size.h); //offset icon

        // RS Pendukung
        rsPendukung = new OpenLayers.Layer.Markers(
            "Depo Pendukung",
            {isBaseLayer: false, visibility: true}
        );

        titik_referensi = new OpenLayers.Layer.Markers("Titik Referensi");
        titik_referensi.setVisibility(false);

        map.addLayers([rsPendukung, titik_referensi]);
        map.redrawSwitcherTree(); //<--- untuk memasukan layer baru ke dlm switcher

        //render marker
        <?php foreach($this->list as $key) : ?>
            ll = new OpenLayers.LonLat(<?php echo $key['x'];?>,<?php echo $key['y'];?>);

/*
        var html = '<p><b><?php //echo $key['nama_depo'];?></b><br/>'
                + '</p>';
*/
    var html = '<table class="list-pendukung">';
        html += '<tr>';
        html += '<th colspan="4" align="center"><?php echo strtoupper($key['nama_depo']);?></th>';
        html += '</tr>';

        html += '<tr>';
        html += '<td>Jenis</td>';
        html += '<td>Kapasitas</td>';
        html += '<td>Current</td>';
        html += '<td>Debit</td>';
        html += '</tr>';

        //avtur
        html += '<tr>';
        html += '<td>Avtur</td>';
        html += '<td><?php echo $key['avtur_kap'];?></td>';
        html += '<td><?php echo $key['avtur_curr'];?></td>';
        html += '<td><?php echo $key['avtur_debit'];?></td>';
        html += '</tr>';

        //hsd
        html += '<tr>';
        html += '<td>HSD</td>';
        html += '<td><?php echo $key['hsd_kap'];?></td>';
        html += '<td><?php echo $key['hsd_curr'];?></td>';
        html += '<td><?php echo $key['hsd_debit'];?></td>';
        html += '</tr>';

        //premium
        html += '<tr>';
        html += '<td>Premium</td>';
        html += '<td><?php echo $key['premium_kap'];?></td>';
        html += '<td><?php echo $key['premium_curr'];?></td>';
        html += '<td><?php echo $key['premium_debit'];?></td>';
        html += '</tr>';

        //solar
        html += '<tr>';
        html += '<td>Solar</td>';
        html += '<td><?php echo $key['solar_kap'];?></td>';
        html += '<td><?php echo $key['solar_curr'];?></td>';
        html += '<td><?php echo $key['solar_debit'];?></td>';
        html += '</tr>';

        html += '</table>';

            popupContentHTML = html;
            var icon = new OpenLayers.Icon(baseUrl + '/images/icons/blue-log-AL.png', size, offset); //object icon
            addMarker(rsPendukung, ll, AutoSizeFramedCloud, popupContentHTML, true, true, icon);
        <?php endforeach; ?>
        changeMarkers();
    });

    function changeMarkers()
    {
        map.events.register('changelayer', null, function(evt){
            if(evt.layer.name == 'Titik Referensi' && titik_referensi.visibility == true){
                parseData(3, 'referensi', '/peta/api/referensi', 0);
            }
        });
    }

    function parseData(id_divisi, jenis, url, matra)
    {
        $.post(baseUrl + url,
            {
                "id_divisi": id_divisi
            },
            function(data){
                if(jenis == 'referensi'){
                    addReferensi(data);
                }
            }, "json");
    }

    function addReferensi(data)
    {
        AutoSizeFramedCloud = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
            'autoSize': true
        });
        popupClass = AutoSizeFramedCloud;

        for(var i in data)
        {
            popupContentHTML = '<table style="width: 250px;">'
                +'<tr>'
                +'<th>'
                + data[i]['keterangan']
                +'</th>'
                +'</tr>'
                +'</table>';

            var iconUrl = baseUrl + '/images/info.png';

            if(data[i]['longitude'] != undefined && data[i]['latitude'] != undefined)
            {
                var realKoordinate = new OpenLayers.LonLat(data[i]['longitude'], data[i]['latitude']);

                var size = new OpenLayers.Size(21,25);
                var offset = new OpenLayers.Pixel(-(size.w/2), -size.h);
                var icon = new OpenLayers.Icon(iconUrl, size, offset);

                addMarker(titik_referensi, realKoordinate, popupClass, popupContentHTML, true, false, icon);
            }
        }
    }
</script>