<?php
$this->inlineScript()->appendFile( $this->jsUrl( 'view/guncategory.js' ) );
?>
<div class="flat_area grid_16">

    <!-- box header label -->
    <h2>Kategori Senjata</h2>

    <!-- toggle button -->
    <a href="#" class="toggle">&nbsp;</a>

    <!-- container -->
    <div class="toggle_container" style="display: block; ">

        <div class="block">

            <table id="table_penyalur" class="display">

                <thead>

                <tr>
                    <th>Kode Kategori Senjata</th>
                    <th>Nama Kategori Senjata</th>
                </tr>
                </thead>

            </table>

        </div>

    </div>

</div>
