<?php $f = $this->element; ?>
<form method="post" action="<?php echo $f->getAction(); ?>" enctype="<?php echo $f->getEnctype(); ?>">
	<?php foreach ($f->getElements() as $el) : ?>
		<?php if ($el->getType() != 'Zend_Form_Element_Submit') : ?>
		<label id="label_<?php echo $el->getName(); ?>"><?php echo $el->getLabel(); ?></label>
			<div class="input_group	">
				<?php echo $el->renderViewHelper(); ?>
				<?php echo $el->renderErrors(); ?>
			</div>
		<?php endif; ?>
	<?php endforeach; ?>
	
	<button class="button_colour round_all" style="float:none">
		<span><?php echo $f->submit->getLabel(); ?></span>
	</button>
</form>