<div class="flat_area grid_16">

	<!-- box header label -->
	<h2>CB Operasional <?php echo $this->kogas; ?></h2>

	<div class="map-top-nav">
		<a href="<?php echo $this->url(array('action'=>'add.cb')); ?>" class="roundall_grey add_icon mr3">
			<span class="ml22">CB Baru</span>
		</a>
		<a href="<?php echo $this->url(array('action'=>'perbandingan')); ?>" class="roundall_grey add_icon mr3">
			<span class="ml22">Perbandingan CB</span>
		</a>
		
		<a href="<?php echo $this->url(array('controller'=>'index','action'=>'index')); ?>" class="roundall_grey back_icon float-right">
			<span class="ml22">Kembali</span>
		</a>
	</div>

	<!-- container -->
	<div class="toggle_container" style="display: block; ">
		<div class="block">
		
			<table id="table-cb" class="display simple-table">
				<thead>
				<tr>
					<th>No CB Operasional</th>
					<th>Waktu Pembuatan</th>
					<th>Action</th>
				</tr>
				</thead>
				<tbody>
					<?php foreach ($this->items as $item) : ?>
					<tr>
						<td><?php echo $item->nomor; ?></td>
						<td><?php echo $item->waktu_pembuatan; ?></td>
						<td>
							<a href="<?php echo $this->url(array('action'=>'edit.cb', 'id'=>$item->id)); ?>">Ubah</a>
							-
							<a href="<?php echo $this->url(array('action'=>'del.cb', 'id'=>$item->id)); ?>" onclick="return confirm('Anda Yakin?')">Hapus</a>
							<?php if (isset($this->ruteClass['udara'])) : ?>
								-
								<a href="<?php echo $this->url(array('action'=>'udara.index', 'cb_id'=>$item->id)); ?>">Rute Udara</a>
							<?php endif; ?>
							<?php if (isset($this->ruteClass['laut'])) : ?>
								-
								<a href="<?php echo $this->url(array('action'=>'laut.index', 'cb_id'=>$item->id)); ?>">Rute Laut</a>
							<?php endif; ?>
							<?php if (isset($this->ruteClass['marinir'])) : ?>
								-
								<a href="<?php echo $this->url(array('action'=>'marinir.index', 'cb_id'=>$item->id)); ?>">Rute Marinir</a>
							<?php endif; ?>
							<?php if (isset($this->ruteClass['darat'])) : ?>
								-
								<a href="<?php echo $this->url(array('action'=>'darat.index', 'cb_id'=>$item->id)); ?>">Rute Darat</a>
							<?php endif; ?>
							<?php if (isset($this->ruteClass['linud'])) : ?>
								-
								<a href="<?php echo $this->url(array('action'=>'linud.index', 'cb_id'=>$item->id)); ?>">Rute Linud</a>
							<?php endif; ?>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			
		</div>
	</div>

</div>
