<div class="flat_area grid_16">

	<!-- box header label -->
	<h2>Rekap Penilaian: CB Operasional <?php echo $this->kogas; ?></h2>

	<div class="map-top-nav">
<!--		<a href="--><?php //echo $this->url(array('action'=>'add.cb')); ?><!--" class="roundall_grey add_icon mr3">-->
<!--			<span class="ml22">CB Baru</span>-->
<!--		</a>-->
<!--		<a href="--><?php //echo $this->url(array('action'=>'perbandingan')); ?><!--" class="roundall_grey add_icon mr3">-->
<!--			<span class="ml22">Perbandingan CB</span>-->
<!--		</a>-->
		
		<a href="<?php echo $this->url(array('controller'=>'penilaian','action'=>'rekap')); ?>" class="roundall_grey back_icon float-right">
			<span class="ml22">Kembali</span>
		</a>
	</div>

	<!-- container -->
	<div class="toggle_container" style="display: block; ">
		<div class="block">
		
			<table id="table-cb" class="display simple-table">
				<thead>
				<tr>
					<th width="40%">No CB Operasional</th>
					<th width="20%">Jenis Rute</th>
					<th width="30%">Nama Rute</th>
					<th width="10%">Nilai</th>
				</tr>
				</thead>
				<tbody>
					<?php foreach ($this->data as $item) : ?>
					<tr>
						<td><?php echo $item['cb']; ?></td>
						<td><?php echo $item['jenis']; ?></td>
						<td><?php echo $item['rute']; ?></td>
						<td align="right">
                            <?php if($item['nilai']): ?>
                            <a href="<?php echo $this->url(array('action'=> $item['jenis'].'.nilai.simulasi', 'cb_id' => $item['cb_id'], 'id'=>$item['rute_id'], 'backurl' => 'rekap.index')); ?>">
                                <?php echo $item['nilai']; ?>
                            </a>
                            <?php else : ?>
                            <?php echo '-'; ?>
                            <?php endif; ?>
                        </td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>
			
		</div>
	</div>

</div>

<script type="text/javascript">
$(function() {
    //Created By: Brij Mohan
    //Website: http://techbrij.com
    function groupTable($rows, startIndex, total){
        if (total === 0){
            return;
        }

        var i , currentIndex = startIndex, count=1, lst=[];
        var tds = $rows.find('td:eq('+ currentIndex +')');
        var ctrl = $(tds[0]);

        lst.push($rows[0]);

        for (i=1;i<=tds.length;i++){
            if (ctrl.text() ==  $(tds[i]).text()){
                count++;
                $(tds[i]).addClass('deleted');
                lst.push($rows[i]);
            }
            else{
                if (count>1){
                    ctrl.attr('rowspan',count);
                    groupTable($(lst),startIndex+1,total-1)
                }
                count=1;
                lst = [];
                ctrl=$(tds[i]);
                lst.push($rows[i]);
            }
        }

    }

    groupTable($('#table-cb tr:has(td)'),0,2);
    $('#table-cb td.deleted').remove();
});
</script>
