<!--<div class="flat_area grid_16">-->
<!--	<h2>Daftar Privilege</h2>-->
<!--	<p>-->
<!--		<a class="roundall_grey add_icon" href="--><?php //echo $this->url(array('action'=>'add')); ?><!--">-->
<!--            <span class="ml22">Tambah Privilege</span>-->
<!--        </a>-->
<!--	</p>-->
<!--	<div class="block">-->
<!--		<table class="display simple-table">-->
<!--			<thead>-->
<!--				<tr>-->
<!--					<th>Name</th>-->
<!--					<th>Module</th>-->
<!--					<th>Controller</th>-->
<!--					<th>Actions</th>-->
<!--					<th></th>-->
<!--				</tr>-->
<!--			</thead>-->
<!--			<tbody>-->
<!--				--><?php //if ($this->items) foreach ($this->items as $i => $item) : ?>
<!--					<tr class="--><?php //echo ($i%2) ? 'even' : 'odd'; ?><!--">-->
<!--						<td>--><?php //echo $item->name; ?><!--</td>-->
<!--						<td>--><?php //echo $item->module; ?><!--</td>-->
<!--						<td>--><?php //echo $item->controller; ?><!--</td>-->
<!--						<td>--><?php //echo $item->actions; ?><!--</td>-->
<!--						<td>-->
<!--							<a href="--><?php //echo $this->url(array('action'=>'edit', 'id'=>$item->id)); ?><!--">Ubah</a> |-->
<!--							<a href="--><?php //echo $this->url(array('action'=>'del', 'id'=>$item->id)); ?><!--" onclick="return confirm('Anda yakin?')">Hapus</a>-->
<!--						</td>-->
<!--					</tr>-->
<!--				--><?php //endforeach; ?>
<!--			</tbody>-->
<!--		</table>-->
<!--	</div>-->
<!--</div>-->


<div class="flat_area grid_16">
    <h2>Daftar Privilege</h2>

    <div class="map-top-nav">
        <a class="roundall_grey add_icon" href="<?php echo $this->url(array('action'=>'add')); ?>">
            <span class="ml22">Tambah Privilege</span>
        </a>
    </div>

    <div class="block">
        <table id="table-dtables" class="display">
            <thead>
            <tr>
                <th>Name</th>
                <th>Module</th>
                <th>Controller</th>
                <th>Action</th>
                <th></th>
            </tr>
            </thead>
        </table>
    </div>
</div>

<script type="text/javascript">
    <?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
    $(function(){
        var oTable = $('#table-dtables').dataTable({
            "bJQueryUI": true,
            "sScrollX": "",
            "bSortClasses": false,
            "aaSorting": [[0,'asc']],
            "bAutoWidth": true,
            "bInfo": true,
            "bFilter": true,
            "sScrollY": "100%",
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "sPaginationType": "full_numbers",
            "bProcessing" : true,
            "bServerSide" : true,
            "sAjaxSource" : '<?php echo $this->url(array('action'=>'dataapi')); ?>',
            "fnServerData" : function(sSource, aoData, fnCallback) {
                jQuery.getJSON(sSource, aoData, function(json) {
                    fnCallback(json);
                });
            },
            'aoColumns' : [
                {bSearchable: false},
                null,null,null,
                {bSortable: false, bSearchable: false, sWidth: '150px'}
            ]
        });

        new Filterer(oTable);
    });
</script>