<div class="box grid_8 round_all" style="margin-top: 10px;">
    <h2 class="box_head grad_colour">Preview Map</h2>
    <div id="map" style="top:-1px"></div>
</div>
<?php //echo $this->render('cbl-rumahsakit/cms-script.phtml');?>

<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
<script type="text/javascript">
    /*
    * cms-script
    * berisi fungsi2 yg digunakan ketika membuat & mengedit rs-pendukung
    * @author : tajhul.faijin@sangkuriang.co.id
    * */
    // global map object
    var map;
    var prevmarkers = new OpenLayers.Layer.Markers( "Preview Position" );
    // layers dan geourl ada di script.js

    //ready function
    $(function(){
        $('#map').css('height', '500px');
        map = standardMap('map');
        map.addLayer(prevmarkers);
        map.events.register('click', map, function(e) {
            var coordinate = map.getLonLatFromViewPortPx( e.xy );
            var lon = coordinate.lon;
            var lat = coordinate.lat;
            document.getElementById('longitude').value = lon;
            document.getElementById('latitude').value = lat;
            previewMarker(lon, lat);
           OpenLayers.Event.stop(e);

        });
    });
    /*
    * <previewMarker> : preview marker
    * @param : lon lat
    * */
    function previewMarker(lon, lat){
        prevmarkers.clearMarkers();
        prevmarkers.addMarker(new OpenLayers.Marker(new OpenLayers.LonLat(lon, lat)));
        var lonLat = new OpenLayers.LonLat(lon, lat);
        map.setCenter (lonLat);
    }

</script>