
<?php $this->headLink()->appendStylesheet( $this->cssUrl( 'print/preview-layout3.css' ), 'screen' )
->appendStylesheet( $this->cssUrl( 'print/print-layout3.css' ),'print' )
;
?>

<?php $i = 1; ?>
<?php if($this->kogas): ?>
    <?php foreach($this->pelaku as $pel): ?>
        <div class="halaman" style="width: 19cm; position: relative; height:24cm; margin-left: 10px; page-break-after:always; display: inline-block;">
            <div class="header-area">
                <div class="header">
                    MARKAS BESAR ANGKATAN LAUT<br/>
                    SEKOLAH STAF DAN KOMANDO
                </div>
                <div class="dateday-area">
                    <span>Hari ................... , </span>
                    <span>Tgl ....................</span>
                </div>
            </div>
            <div style="width: 100%; text-align: center; clear: both;">
                <h3 style="margin-bottom: 0;">PENILAIAN PARTISIPASI PERORANGAN</h3>
                <h3 style="margin-top: 0;"><?php echo $this->scenario; ?></h3>
            </div>
            <div><h3 style="margin-left: 50px;"><?php echo $this->kogas; ?></h3></div>
            <div style="position: relative;">
                <table class="btable">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Pasis</th>
                            <th>Pangkat</th>
                            <th>NRP</th>
                            <th width="15%">Nilai Partisipasi</th>
                            <th width="20%">KET</th>
                        </tr>
                        <tr class="no-padding">
                            <th>1</th>
                            <th>2</th>
                            <th>3</th>
                            <th>4</th>
                            <th>5</th>
                            <th>6</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if(!empty($pel)): ?>
                        <?php foreach($pel as $pelDetail): ?>
                        <tr>
                            <td style="text-align: center;">
                                <?php echo $i.'.'; ?>
                            </td>
                            <td><?php echo $pelDetail['nama']; ?></td>
                            <td><?php echo $pelDetail['pangkat']; ?></td>
                            <td style="text-align: center;"><?php echo $pelDetail['nrp'] ? $pelDetail['nrp'] : ''; ?></td>
                            <td style="text-align: center;"><?php echo $pelDetail['nilai']; ?></td>
                            <td style="text-align: center;"><?php echo $pelDetail['keterangan'];?></td>
                        </tr>
                            <?php $i++; endforeach; ?>
                        <?php endif; ?>
                    </tbody>
                </table>
            </div>
            <div class="ftable-wrapper" style="left: 60%; width: 40%;">
                <table>
                    <thead>
                        <tr>
                            <th colspan="3">PENILAI</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Nama</td>
                            <td>:</td>
                            <td><?php echo $this->penilai['nama'];?></td>
                        </tr>
                        <tr>
                            <td>PKT/KORPS/NRP</td>
                            <td>:</td>
                            <td><?php echo $this->penilai['pangkat'].' / - / '.$this->penilai['nrp'];?></td>
                        </tr>
                        <tr>
                            <td>Tanda Tangan</td>
                            <td>:</td>
                            <td height="50px"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endforeach; ?>
<?php else: ?>
    <h1>Mohon maaf, anda tidak memiliki hak akses.</h1>
<?php endif;?>