<div class="flat_area grid_16">
    <p><a href="<?php echo $this->url(array('action'=>'index')); ?>">Kembali</a></p>
</div>
<div class="box grid_16 round_all">
    <h2 class="box_head grad_colour">Tambah Telegram</h2>
    <div class="toggle_container">
        <div class="block">
            <?php
            $this->form->setAction($this->url());
            echo $this->form;
            ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    $('.to').hide();
    $('label:contains(Terjadwal)').remove();
    $('#terjadwal').remove();
    $('#datehide').hide();
//    $('#terjadwal').click(function(){
//        $('#datehide').toggle();
//    });
//
//    $('.tgl').datetimepicker({
//        changeYear: true,
//        changeMonth: true
//    });

</script>