<?php
$this->inlineScript()->appendFile( $this->jsUrl( 'view/cb-operasional-list.js' ) );
?>
<div class="flat_area grid_16">

    <!-- box header label -->
    <h2>CB Operasional Kogasgabla</h2>

    <div class="map-top-nav">
        <a href="<?php echo $this->url(array('controller'=>'operasional','action'=>'addcboperasional')); ?>" class="roundall_grey add_icon mr3">
            <span class="ml22">CB Baru</span>
        </a>
        <a href="<?php echo $this->url(array('controller'=>'operasional','action'=>'perbandingan')); ?>" class="roundall_grey add_icon mr3">
            <span class="ml22">Perbandingan CB Laut</span>
        </a>
        <a href="<?php echo $this->url(array('controller'=>'operasional','action'=>'udara.perbandingan')); ?>" class="roundall_grey add_icon mr3">
            <span class="ml22">Perbandingan CB Udara</span>
        </a>
		
		<a href="<?php echo $this->url(array('action'=>'index')); ?>" class="roundall_grey back_icon float-right">
			<span class="ml22">Kembali</span>
		</a>
    </div>

    <!-- container -->
    <div class="toggle_container" style="display: block; ">

        <div class="block">
            <table id="table_penyalur" class="display">
                <thead>
                <tr>
                    <th>No CB Operasional</th>
                    <th>Waktu Pembuatan</th>
                    <th>Action</th>
                </tr>
                </thead>

            </table>

        </div>

    </div>

</div>
