<!-- PDFJSSCRIPT_INCLUDE_BUILD -->
<?php $this->headLink()->appendStylesheet( $this->jsUrl( 'new_pdfjs/viewer.css' ) ); ?>
<?php $this->headLink()->headLink( array('rel' => 'resource', 'type' => "application/l10n", 'href' => 'locale.properties'), 'PREPEND'); ?>
<?php $this->headScript()->appendFile( $this->jsUrl('new_pdfjs/compatibility.js')); ?>
<?php $this->headScript()->appendFile( $this->jsUrl('new_pdfjs/external/webL10n/l10n.js')); ?>

<?php
$jss = array(
	'core.js', 'util.js', 'api.js', 'metadata.js', 'canvas.js', 'obj.js', 'function.js',
	'charsets.js', 'cidmaps.js', 'colorspace.js', 'crypto.js', 'evaluator.js', 'fonts.js',
	'glyphlist.js', 'image.js', 'metrics.js', 'parser.js', 'pattern.js', 'stream.js', 'worker.js'
);
foreach ($jss as $js) {
	$this->headScript()->appendFile($this->jsUrl('new_pdfjs/src/'.$js));
}
$this->headScript()->appendFile($this->jsUrl('new_pdfjs/external/jpgjs/jpg.js'))
	->appendFile($this->jsUrl('new_pdfjs/src/jpx.js'))
	->appendFile($this->jsUrl('new_pdfjs/src/bidi.js'));
?>

<script type="text/javascript">
	var value = '<?php echo $this->nilai['nilai']; ?>';

	PDFJS.workerSrc = '<?php echo $this->jsUrl('new_pdfjs/src/worker_loader.js'); ?>';
	kDefaultURL = '<?php echo $this->siteUrl($this->ref->get('filepath')); ?>';

	$(function(){
//		$('button').live('click', function(){
//			return false;
//		});

		$('.slider-input').keyup(function(){
			thisElmVal = $(this).val();
			if(thisElmVal > 100){
				alert('asdfasdf')
			}
			else
			{
				$(this).parent().parent().find('.slider').slider('value', thisElmVal);
			}
		});

		$( ".slider" ).slider({
			range:"min",
			value:value,
			min: 0,
			max: 100,
			step: 1,
			slide: function( event, ui ) {
				$(this).parent('td').find('input').val(ui.value);
			}
		});
		//$( "#amount" ).val( $( ".slider" ).slider( "value" ) );

	});
</script> <!-- PDFJSSCRIPT_REMOVE_CORE -->

<?php
$this->headScript()->appendFile($this->jsUrl('new_pdfjs/debugger.js'))
	->appendFile($this->jsUrl('new_pdfjs/viewer.js'));
?>

<div class="flat_area grid_16">
	<h2>Form Penilaian</h2>
	<div>
		<div class="block grid_12" style="margin: 0 auto; margin-left: 20px;">
			<table class="display simple-table">
				<thead>
				<tr>
					<th>Nama Produk Staff</th>
					<th>Pengirim</th>
					<th>Tanggal dan Jam Penyimpanan</th>
				</tr>
				</thead>
				<tbody>

				<tr>
					<td><?php echo $this->data['nama_product_staff']; //'nama produk staff';//$this->data['nrp']; ?></td>
					<td><?php echo $this->data['team_name']; //'nama team pengirim';//$this->data['nama']; ?></td>
					<td><?php echo $this->data['datetime']; //'tanggal dan jam penyimpanan';//'$this->data['nama_jabatan']; ?></td>
				</tr>
				<tr>
					<td colspan="3" id="pdfarea">
						<div id="outerContainer">

							<div id="sidebarContainer">
								<div id="toolbarSidebar">
									<button id="viewThumbnail" class="toolbarButton group toggled" title="Show Thumbnails" onclick="PDFView.switchSidebarView('thumbs')" tabindex="1" data-l10n-id="thumbs">
										<span data-l10n-id="thumbs_label">Thumbnails</span>
									</button>
									<button id="viewOutline" class="toolbarButton group" title="Show Document Outline" onclick="PDFView.switchSidebarView('outline')" tabindex="2" data-l10n-id="outline">
										<span data-l10n-id="outline_label">Document Outline</span>
									</button>
									<button id="viewSearch" class="toolbarButton group hidden" title="Search Document" onclick="PDFView.switchSidebarView('search')" tabindex="3" data-l10n-id="search_panel">
										<span data-l10n-id="search_panel_label">Search Document</span>
									</button>
								</div>
								<div id="sidebarContent">
									<div id="thumbnailView">
									</div>
									<div id="outlineView" class="hidden">
									</div>
									<div id="searchView" class="hidden">
										<div id="searchToolbar">
											<input id="searchTermsInput" onkeydown='if (event.keyCode == 13) PDFView.search()'>
											<button id="searchButton" onclick='PDFView.search()' data-l10n-id="search">Find</button>
										</div>
										<div id="searchResults"></div>
									</div>
								</div>
							</div>  <!-- sidebarContainer -->

							<div id="mainContainer">
								<div class="toolbar">
									<div id="toolbarContainer">

										<div id="toolbarViewer">
											<div id="toolbarViewerLeft">
												<button id="sidebarToggle" class="toolbarButton" title="Toggle Sidebar" tabindex="4" data-l10n-id="toggle_slider">
													<span data-l10n-id="toggle_slider_label">Toggle Sidebar</span>
												</button>
												<div class="toolbarButtonSpacer"></div>
												<div class="splitToolbarButton">
													<button class="toolbarButton pageUp" title="Previous Page" onclick="PDFView.page--" id="previous" tabindex="5" data-l10n-id="previous">
														<span data-l10n-id="previous_label">Previous</span>
													</button>
													<div class="splitToolbarButtonSeparator"></div>
													<button class="toolbarButton pageDown" title="Next Page" onclick="PDFView.page++" id="next" tabindex="6" data-l10n-id="next">
														<span data-l10n-id="next_label">Next</span>
													</button>
												</div>
												<label id="pageNumberLabel" class="toolbarLabel" for="pageNumber" data-l10n-id="page_label">Page: </label>
												<input type="number" id="pageNumber" class="toolbarField pageNumber" onchange="PDFView.page = this.value;" value="1" size="4" min="1" tabindex="7">
												</input>
												<span id="numPages" class="toolbarLabel"></span>
											</div>
											<div id="toolbarViewerRight">
												<input id="fileInput" class="fileInput" type="file" oncontextmenu="return false;" style="visibility: hidden; position: fixed; right: 0; top: 0" />


												<!--
<button id="print" class="toolbarButton print" title="Print" tabindex="11" data-l10n-id="print" onclick="window.print()">
  <span data-l10n-id="print_label">Print</span>
</button>
-->

												<button id="download" class="toolbarButton download" title="Download" onclick="PDFView.download();" tabindex="12" data-l10n-id="download">
													<span data-l10n-id="download_label">Download</span>
												</button>
												<!-- <div class="toolbarButtonSpacer"></div> -->
												<a href="#" id="viewBookmark" class="toolbarButton bookmark" title="Current view (copy or open in new window)" tabindex="13" data-l10n-id="bookmark"><span data-l10n-id="bookmark_label">Current View</span></a>
											</div>
											<div class="outerCenter">
												<div class="innerCenter" id="toolbarViewerMiddle">
													<div class="splitToolbarButton">
														<button class="toolbarButton zoomOut" title="Zoom Out" onclick="PDFView.zoomOut();" tabindex="8" data-l10n-id="zoom_out">
															<span data-l10n-id="zoom_out_label">Zoom Out</span>
														</button>
														<div class="splitToolbarButtonSeparator"></div>
														<button class="toolbarButton zoomIn" title="Zoom In" onclick="PDFView.zoomIn();" tabindex="9" data-l10n-id="zoom_in">
															<span data-l10n-id="zoom_in_label">Zoom In</span>
														</button>
													</div>
				  <span id="scaleSelectContainer" class="dropdownToolbarButton">
					 <select id="scaleSelect" onchange="PDFView.parseScale(this.value);" title="Zoom" oncontextmenu="return false;" tabindex="10" data-l10n-id="zoom">
						 <option id="pageAutoOption" value="auto" selected="selected" data-l10n-id="page_scale_auto">Automatic Zoom</option>
						 <option id="pageActualOption" value="page-actual" data-l10n-id="page_scale_actual">Actual Size</option>
						 <option id="pageFitOption" value="page-fit" data-l10n-id="page_scale_fit">Fit Page</option>
						 <option id="pageWidthOption" value="page-width" data-l10n-id="page_scale_width">Full Width</option>
						 <option id="customScaleOption" value="custom"></option>
						 <option value="0.5">50%</option>
						 <option value="0.75">75%</option>
						 <option value="1">100%</option>
						 <option value="1.25">125%</option>
						 <option value="1.5">150%</option>
						 <option value="2">200%</option>
					 </select>
				  </span>
												</div>
											</div>
										</div>
									</div>
								</div>

								<div id="viewerContainer">
									<div id="viewer"></div>
								</div>

								<div id="loadingBox">
									<div id="loading" data-l10n-id="loading" data-l10n-args='{"percent": 0}'>Loading... 0%</div>
									<div id="loadingBar"><div class="progress"></div></div>
								</div>

								<div id="errorWrapper" hidden='true'>
									<div id="errorMessageLeft">
										<span id="errorMessage"></span>
										<button id="errorShowMore" onclick="" oncontextmenu="return false;" data-l10n-id="error_more_info">
											More Information
										</button>
										<button id="errorShowLess" onclick="" oncontextmenu="return false;" data-l10n-id="error_less_info" hidden='true'>
											Less Information
										</button>
									</div>
									<div id="errorMessageRight">
										<button id="errorClose" oncontextmenu="return false;" data-l10n-id="error_close">
											Close
										</button>
									</div>
									<div class="clearBoth"></div>
									<textarea id="errorMoreInfo" hidden='true' readonly="readonly"></textarea>
								</div>
							</div> <!-- mainContainer -->

						</div> <!-- outerContainer -->
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<form method="post" action="<?php echo $this->url(array('controller' => 'penilaian','action'=>'save')); ?>">
							<table class="simple-table" style="margin-bottom: 0; width: 100%;">
								<tr>
									<th width="20%">Penilaian</th>
									<td class="block">
										<input type="text" class="slider-input" maxlength="3" size="3"
											   name="nilai" id="nilai" value="<?php echo $this->nilai['nilai']; ?>"
											   style="text-align:right;font-weight:bold;" />
										<div class="slider"></div>
									</td>
								</tr>
								<tr>
									<th>Catatan</th>
									<td class="block">
										<textarea rows="2" cols="140" name="keterangan" id="keterangan"><?php echo $this->nilai['keterangan']; ?></textarea>
									</td>
								</tr>
								<tr>
									<td colspan="3" class="block">
                                        <input type="hidden" value="<?php echo $this->data['id_produk_staff']; ?>" name="id_ps" />
                                        <input type="hidden" value="<?php echo $this->data['id_team']; ?>" name="id_team" />
										<button class="button_colour round_all" style="float: right;">
											<span>Simpan</span>
										</button>
									</td>
								</tr>
							</table>
						</form>
					</td>
				</tr>
				</tbody>
			</table>
		</div>
</div>
