<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour"></h2>
	<div class="toggle_container">
		<div class="block">
			<ul>
				<li><a href="<?php echo $this->url(array('controller'=>'role', 'action'=>'index')); ?>">
					Manajemen Role
				</a></li>
				<li><a href="<?php echo $this->url(array('controller'=>'login', 'action'=>'index')); ?>">
					Manajemen Login
				</a></li>
				<li><a href="<?php echo $this->url(array('controller'=>'privilege', 'action'=>'index')); ?>">
					Manajemen Privilege
				</a></li>
				<li><a href="<?php echo $this->url(array('controller'=>'role.privilege', 'action'=>'index')); ?>">
					Manajemen Role Privilege
				</a></li>
			</ul>
		</div>
	</div>
</div>
