<div class="flat_area grid_16">

	<!-- box header label -->
	<h2>Setting Taktis</h2>

	<div class="map-top-nav">
        <a href="<?php echo $this->url(array('controller'=>'rencana.operasi.sendiri', 'action'=>'index')); ?>" class="roundall_grey add_icon mr3">
            <span class="ml22">Taktis Sendiri</span>
        </a>
        <a href="<?php echo $this->url(array('controller'=>'rencana.operasi.musuh', 'action'=>'index')); ?>" class="roundall_grey add_icon mr3">
            <span class="ml22">Taktis Musuh</span>
        </a>
	</div>

	<!-- container -->
	<div class="block">
		<!-- what to write here? -->
	</div>
	
</div>
