<div class="map-top-nav grid_16">
    <a href="<?php echo $this->url(array('action'=>'list')); ?>" class="roundall_grey add_icon float-left">
        <span class="ml22">Rumah Sakit Umum Pendukung</span>
    </a>

    <a href="<?php echo $this->url(array('controller'=>'cb-logistik','action'=>'detail','cbid'=>$this->cbid->getId())); ?>" class="roundall_grey add_icon float-right">
        <span class="ml22">Kembali</span>
    </a>
</div>

<div class="box grid_8 grid_16 round_all contentmap " >
    <h2 class="box_head grad_colour titlemap">
        <span>Rumah Sakit Pendukung</span>
    </h2>
    <div id="map" style="top: -1px"></div>
</div>

<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
<script>

    // global map object
    var map;
    var rsPendukung;
    // layers dan geourl ada di script.js

    $(function(){
        $('#map').css('height', '500px');
        map = standardMap('map');

        // Marker Pangkalan Pendukung
        var ll, popupContentHTML;
        var AutoSizeFramedCloud = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
            'autoSize': true
        });
        //-- icon --
        var size = new OpenLayers.Size(27,27); // size icon
        var offset = new OpenLayers.Pixel(-(size.w/2), -size.h); //offset icon

        // RS Pendukung
        rsPendukung = new OpenLayers.Layer.Markers(
            "Rumah Sakit Pendukung",
            {isBaseLayer: false, visibility: true}
        );
        map.addLayer(rsPendukung);
        map.redrawSwitcherTree(); //<--- untuk memasukan layer baru ke dlm switcher

        //render marker RS pendukung
        <?php foreach($this->rspendukung as $key) : ?>
            ll = new OpenLayers.LonLat(<?php echo $key['y'];?>,<?php echo $key['x'];?>);
            popupContentHTML = '<p><b><?php echo $key['nama'];?></b></p>';
            var icon = new OpenLayers.Icon(baseUrl + '/images/icons/cross.png', size, offset); //object icon
            addMarker(rsPendukung, ll, AutoSizeFramedCloud, popupContentHTML, true, true, icon);
        <?php endforeach; ?>

    });
</script>

