<div class="flat_area grid_16">
	<h2>Detail Skenario Latihan</h2>
	
	<a href="<?php echo $this->url(array('action'=>'index', 'id'=>null)); ?>" class="roundall_grey back_icon float-right">
		<span class="ml22">Kembali</span>
	</a>
	
	<p class="roundall_grey grid_4">
		<img src="" alt="Logo">
		<a href="<?php echo $this->url(array('controller'=>'kekuatan.sendiri','action'=>'index')); ?>">
			Persebaran Kekuatan Sendiri
		</a>
	</p>
	<p class="roundall_grey grid_4">
		<img src="" alt="Logo">
		<a href="<?php echo $this->url(array('controller'=>'kekuatan.lawan','action'=>'index')); ?>">
			Persebaran Kekuatan Musuh
		</a>
	</p>
<!--	<p class="roundall_grey grid_4">-->
<!--		<img src="" alt="Logo">-->
<!--		<a href="--><?php //echo $this->url(array('controller'=>'kekuatan.musuh','action'=>'index')); ?><!--">-->
<!--			Persebaran Kekuatan Musuh-->
<!--		</a>-->
<!--	</p>-->
	<p class="roundall_grey grid_4">
		<img src="" alt="Logo">
		<a href="<?php echo $this->url(array('action'=>'buku')); ?>">
			Upload Buku I &amp; Buku II
		</a>
	</p>
    <!--
	<p class="roundall_grey grid_4">
		<img src="" alt="Logo">
		<a href="<?php // echo $this->url(array('module'=>'peta','controller'=>'intelijen','action'=>'index')); ?>">
			Peta Intelijen
		</a>
	</p>
	<p class="roundall_grey grid_4">
		<img src="" alt="Logo">
		<a href="<?php // echo $this->url(array('module'=>'peta','controller'=>'operasional','action'=>'index')); ?>">
			Peta Operasional
		</a>
	</p> -->
</div>
