<style type="text/css">
    #controlToggle li {
        list-style: none;
    }
    p {
        width: 512px;
    }
    /* avoid pink tiles */
    .olImageLoadError {
        background-color: transparent !important;
    }
</style>
<div class="grid_16">
    <div class="map-top-nav">
        <a href="<?php echo $this->siteUrl('latihan/kekuatan.musuh/darat/skenario_id/' . $this->skenario->getId());?>" class="roundall_grey back_icon float-right">
        <span class="ml22">Kembali</span>
        </a>
    </div>
</div>
<div class="box grid_8 round_all" style="clear: both;">
    <h2 class="box_head grad_colour">Form Kekuatan Darat</h2>
    <div class="toggle_container">
        <div class="block">
            <form method="post" id="form-kekuatan" action="<?php echo $this->url(); ?>">
                <label for="lokasi">Nama Lokasi</label>
                <input type="text" name="txtLokasi" id="lokasi">

                <label for="longitude">Longitude</label>
	            <input id="conv-lon-deg" size="2" style="display:inline">&deg;
	            <input id="conv-lon-min" size="2" style="display:inline">'
	            <input id="conv-lon-sec" size="2" style="display:inline">"
	            <select id="conv-lon-dir"><option>T</option><option>B</option></select>
	            <button id="conv-lon-conv" type="button" style="display:inline;float:none">Convert</button>
                <input type="text" name="txtLongitude" id="longitude">

                <label for="latitude">Latitude</label>
	            <input id="conv-lat-deg" size="2" style="display:inline">&deg;
	            <input id="conv-lat-min" size="2" style="display:inline">'
	            <input id="conv-lat-sec" size="2" style="display:inline">"
	            <select id="conv-lat-dir"><option>U</option><option>S</option></select>
	            <button id="conv-lat-conv" type="button" style="display:inline;float:none">Convert</button>
                <input type="text" name="txtLatitude" id="latitude">

                <table id="kekuatan-table" class="simple-table">
                    <tr>
                        <th>Kesatuan</th>
                        <th>Tingkat Kesatuan</th>
                        <th width="5%">Jumlah</th>
                        <th>Keterangan</th>
                        <th width="8%"></th>
                    </tr>
                </table>
                <button id="button-tambah-row" type="button">+Tambah</button>
                <button type="submit" id="button-save" class="button_colour round_all">
                    <span>Simpan</span>
                </button>
            </form>
        </div>
    </div>
</div>

<?php echo $this->render('partials/map-cms-kekuatan.phtml');?>

<?php
//simbol untuk AD
$jenisSimbol = array(
    'm infantri',
    'm infantri mekanis',
    'm linud',
    'm kavaleri roda',
    'm kavaleri tank',
    'm artileri medan',
    'm artileri hanud',
    'm zeni',
    'm teritorial',
    'm sayap putar',
    'm sayap tetap'
);
?>
<script type="text/javascript">
    var kekuatanMusuh = 'musuh';
    //global variable
    var optionsUnsurArr = [];
    var optionsJenis = [];
    <?php foreach($this->jenis as $jenis): ?>
        <?php if(in_array($jenis['jenis'], $jenisSimbol)) :?>
            optionsUnsurArr.push('<?php echo $jenis['jenis']; ?>');
            optionsJenis.push({
                '<?php echo $jenis['jenis']; ?>': <?php echo json_encode($this->simTaktis->getAll('jenis', $jenis['jenis'], null, false)); ?>
            });
        <?php endif;?>
    <?php endforeach; ?>

    var optionsUnsur = optionsUnsurArr;
    var globali = 0;
    //end global variable

    function tambah_row(id, unsur, jenis, jumlah, keterangan) {

        //@author : tajhul faijin
        //validasi inputan jumlah pada row sebelumnya tidak boleh kosong
        if( globali > 0 ){
            var prevIndex = globali - 1;
            var domValue = $('#kekuatan-table').find('input[name="detail['+ prevIndex +'][jumlah]"]');
            var prevValue = domValue.val();

            if( prevValue == '' ){
                alert('Jumlah Tidak boleh kosong!');
                domValue.focus();
                return false;
            }
        }
        /*
      <tr>
          input hidden id[]
          td select unsur[]
          td select jenis[]
          td jumlah[]
          td button hapus_row(this)
      </tr>
      */
        var $tr = $('<tr/>');

        var $hidden = $('<input type="hidden" name="detail['+globali+'][id]" />');
        if (id) {
            $hidden.val(id);
        }

        var $select1 = $('<select name="detail['+globali+'][jenis]" />');
        // populate options
        for (var i=0,inum=optionsUnsur.length; i<inum; i++) {
            var val = optionsUnsur[i];
            $select1.append('<option value="'+val+'">'+val+'</option>');
        }
        if (unsur) {
            $select1.val(unsur);
        }
        $select1.appendTo($tr).wrap('<td>').uniform();
        // sisipkan $hidden
        $hidden.insertAfter($select1);

        var $select2 = $('<select name="detail['+globali+'][taktis_id]" />');
        // populate options berdasarkan nilai $select1
        $select1.bind('change', function(e) {
            // @TODO bug element select theme adminica
            $select2.empty();
            for (var i=0,inum=optionsJenis.length; i<inum; i++) {
                var options = optionsJenis[i][$select1.val()];
                if (options) {
                    for (var x=0,xnum=options.length; x<xnum; x++) {
                        var index = options[x]['id'];
                        var val = options[x]['nama'];
                        $select2.append('<option value="'+index+'">'+val+'</option>');
                    }
                }
            }

            if ($.uniform.update) {
                $.uniform.update($select2);
            }
        });
        $select1.trigger('change');
        if (jenis) {
            $select2.val(jenis);
        }
        $select2.appendTo($tr).wrap('<td>').uniform();

        var $input = $('<input style="width: 55px;" name="detail['+globali+'][jumlah]" />');
        if (jumlah) {
            $input.val(jumlah);
        }
        $input.appendTo($tr).wrap('<td>');

        var $textarea = $('<textarea style="width: 120px;" name="detail['+globali+'][keterangan]"></textarea>');
        if (keterangan) {
            $textarea.val(keterangan);
        }
        $textarea.appendTo($tr).wrap('<td>');

        //@author : tajhul faijin
        //jika bukan row pertama, kasih tombol x untuk menghapus row
        // FYI : globali = var global yg berisi index yg dimulai dari 0 (nol)
        if(globali > 0){
            var $button = $('<button type="button" onclick="hapus_row(this)" />');
            $button.html('X');
            $button.appendTo($tr).wrap('<td>');
        } else {
            //jika row pertama buatkan cell kosong saja
            //FYI : agar row table tidak berantakan
            $('<span>&nbsp;</span>').appendTo($tr).wrap('<td>');
        }

        $('#kekuatan-table').append($tr);
        globali++;
    }

    function hapus_row(el) {
        $(el).parent().parent().remove();
    }

    //ready function
    $(function() {
        tambah_row(); //create row onload

        //validasi ketika submit
        $('#form-kekuatan').bind('submit', function(){

            //validasi textbox sederhana dgn menggunakan flag array
            var valids = []; //array untuk flag
            $('#form-kekuatan input[type="text"]').each(function(){
                var value = $(this).val();
                if(value == ''){
                    valids.push(0); //jika kosong
                } else {
                    valids.push(1); //jika isi
                }
            });
            //kemudian cek flag array valids,
            // jika terdapat nilai flag 0 dlm array berarti masih ada yg kosong
            if( in_array(0, valids) ){
                alert('Semua teks field harus diisi!');
                return false;
            } else {
                return true;
            }
        })
        $('#button-tambah-row').bind('click', function(e) {
            tambah_row();
        });

        // populate saved data
        <?php //foreach ($this->model->all() as $e) : ?>
            //tambah_row(<?php
//                echo json_encode($e->id).',';
//                echo json_encode($e->unsur).',';
//                echo json_encode($e->jenis).',';
//                echo json_encode($e->jumlah);
                ?>);
        <?php //endforeach; ?>
    });

	//conversi DMS ke DD
	$(function(){
		var convertDms = function (pid, idlonlat) {
			var $ipt = $('#'+idlonlat),
				deg = parseInt($('#conv-'+pid+'-deg').val(), 10),
				min = parseInt($('#conv-'+pid+'-min').val(), 10),
				sec = parseInt($('#conv-'+pid+'-sec').val(), 10),
				dir = $('#conv-'+pid+'-dir').val(),
				result;

			if (!isNaN(deg) && !isNaN(min) && !isNaN(sec)) {
				result = deg + (min*60 + sec)/3600;
				if (dir == 'S' || dir == 'T') {
					result = -1 * result;
				}
				$ipt.val(result);
				$ipt.trigger('change');
			}
			$ipt.focus();
		};
		$('#conv-lon-conv').bind('click', function(e) {
			convertDms('lon', 'longitude');
		});
		$('#conv-lat-conv').bind('click', function(e) {
			convertDms('lat', 'latitude');
		});
	});
</script>