<?php $this->headStyle()->captureStart(); ?>
#animator-toolbar button {
	float:none;
	display: inline-block;
}
<?php $this->headStyle()->captureEnd(); ?>

<div class="flat_area grid_16">
	<a href="<?php echo $this->url(array('action'=>'index', 'id'=>null, 'cbid'=>$this->model->getCbId())); ?>" class="roundall_grey back_icon float-right">
		<span class="ml22">Kembali</span>
	</a>	
</div>

<div class="box grid_16 round_all">
	<h2 class="box_head grad_colour">Simulasi Rute Operasional : <?php echo $this->model->getNama(); ?></h2>
	
	<div id="map2"></div>
	
	<div class="block" id="animator-toolbar">
		<button id="button-start" type="button">Start</button>
		<button id="button-pause" type="button">Pause</button>
		<button id="button-reset" type="button">Reset</button>
		Waktu asumsi 1 detik = <input id="second2hour" value="1"> jam
		<div class="float-right">Total jarak tempuh: <span id="jarak-cb">0</span> nautical mile</div>
		
		<div id="time-slider"></div>
		State: <span id="time-notice">0</span>
	</div>
</div>

<?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>
<?php $this->inlineScript()->appendFile($this->jsUrl('view/rute-operasional.js')); ?>
<?php $this->inlineScript()->appendFile($this->jsUrl('view/rute-animator.js')); ?>
<?php $this->inlineScript()->appendFile($this->jsUrl('view/rute-statistik.js')); ?>
<script>

var animator,
	stats,
	resetFlag = true;

$(function() {
	"use strict";
	var map,
		layerVector,
		tempTitik, 
		tempFormasi,
		$asumsi,
		latumLayer, format;
		
	// inisiasi map
	$asumsi = $('#second2hour').css('display', 'inline');
	$('#map2').css('height', '500px');
	map = standardMap('map2');
	layerVector = new OpenLayers.Layer.Vector('Rute', {
		displayInLayerSwitcher:false
	});
	map.addLayer(layerVector);
	// refresh features after zooming
	map.events.register('zoomend', map, function (e) {
		animator.redraw();
	});
	
	// animasi menggunakan multi-formasi untuk reuseability
	animator = new Animator_Multi_Formasi(layerVector);
	stats = new Statistik_Cb();
	tempTitik = <?php echo json_encode($this->model->getTitik()); ?>;
	tempFormasi = <?php echo json_encode($this->model->getFormasi()); ?>;
	animator.addItem(tempFormasi, tempTitik);
	stats.addFormasi(tempFormasi, tempTitik);
	
	// tampilkan jarak
	$('#jarak-cb').html(stats.totalJarakInNauMile().toFixed(3));
	
	// inisiasi tombol
	$asumsi.bind('change', function(e) {
		resetFlag = true;
	});
	$('#button-start').bind('click', function(e) {
		if (resetFlag) {
			animator.generateState(parseInt($asumsi.val(), 10), 'knot');
			resetFlag = false;
		}
		animator.startAnimation();
	});
	$('#button-pause').bind('click', function(e) {
		animator.stopAnimation();
	});
	$('#button-reset').bind('click', function(e) {
		animator.resetAnimation();
	});
	
	// tampilkan polygon latum
	latumLayer = new OpenLayers.Layer.Vector("Latihan Umum", {displayInLayerSwitcher: false});
	map.addLayer(latumLayer);
	<?php $latum = $this->model->getLatum(); ?>
	<?php if ($latum) : ?>
		format = new OpenLayers.Format.WKT();
		latumLayer.addFeatures([format.read(<?php echo json_encode($latum); ?>)]);
	<?php endif; ?>
	
});
</script>