<?php $this->printGoBackUrl($this->baseUrl('latihan/sheet/sheet-upload')); ?>
<div class="flat_area grid_16" style="margin-bottom: 20px;margin-top: 5px;">
	<h2>ROL - <?php echo $this->data['nama']; ?></h2>
	<div class="" style="height: 500px;overflow: scroll;">
        <?php echo $this->file; ?>
        <!--		<iframe style="background-color: #fff;" src="<?php /*echo $this->baseUrl($this->data['filepath']);*/?>" height="450" class="grid_16">
		</iframe>-->
	</div>
</div>