<?php $this->headStyle()->captureStart(); ?>
#select-username {
float: left;
width: 10%;
}

#jenis-pohon li {
border: none;
padding: 0;
}

#jenis-pohon li a {
color: black;
}

#table-dtables_wrapper {
float: right;
width: 87%;
}

#table-dtables_processing {
float: none;
width: 80px;
}
<?php $this->headStyle()->captureEnd(); ?>
<div class="flat_area grid_16">
    <h2>Daftar Log</h2>

    <div class="block">
        <select id="select-username" multiple="multiple" size="8" >
            <?php foreach($this->dataLogin as $data): ?>
                <option value="<?php echo $data['id']; ?>"><?php echo $data['username']; ?></option>
            <?php endforeach; ?>
        </select>
        <table id="table-dtables" class="display">
            <thead>
            <tr>
                <th width="136">Waktu</th>
                <th width="160">No Telegram</th>
                <th>User Name</th>
                <th>Kepada</th>
                <th>Tembusan</th>
                <th>Jadwal</th>
                <th>Team</th>
            </tr>
            </thead>
        </table>
    </div>
</div>

<script type="text/javascript">
    <?php $this->inlineScript()->appendFile($this->jsUrl('script.js')); ?>

    $(function(){
        var oTable = $('#table-dtables').dataTable({
            "bJQueryUI": true,
            "sScrollX": "",
            "bSortClasses": false,
            "aaSorting": [[0,'asc']],
            "bAutoWidth": true,
            "bInfo": true,
            "bFilter": true,
            "sScrollY": "100%",
            "sScrollX": "100%",
            "bScrollCollapse": true,
            "sPaginationType": "full_numbers",
            "bProcessing" : true,
            "bServerSide" : true,
            "sAjaxSource" : '<?php echo $this->url(array('action'=>'dataapi')); ?>',
            "fnServerData" : function(sSource, aoData, fnCallback) {
                var nilai = $('#select-username option:selected').val();
                aoData.push({
                    'name': 'value',
                    'value': nilai
                });
                // @optional filter category content
                jQuery.getJSON(sSource, aoData, function(json) {
                    fnCallback(json);
                });
            },
            'aoColumns' : [
                null,null,null,null,null,null,null]
        });

        new Filterer(oTable);

        $('#select-username').live('click', function(e) {
            oTable.fnDraw();
        });

    });
</script>