<div class="box grid_8 round_all">
	<h2 class="box_head grad_colour">Tambah Depo Pendukung</h2>
	<div class="toggle_container">
		<div class="block">
			<?php 
			$this->form->setAction($this->url());
			echo $this->form;
			?>
		</div>
	</div>
</div>

<div class="flat_area grid_16">
	<p><a href="<?php echo $this->url(array('action'=>'list')); ?>">Kembali</a></p>
</div>

<script type="text/javascript">
</script>