<div class="flat_area grid_16">
	<h2>Daftar Persenjataan</h2>
	
	<div class="block">
		<table id="table-weapon" class="display">
			<thead>
				<tr>
					<th>Ship Name</th>
					<th>Bomb Count</th>
					<th>Radar Count</th>
					<th>Sonar Count</th>
					<th></th>
				</tr>
			</thead>
		</table>
	</div>
</div>

<script type="text/javascript">
$(function(){
    var oTable = $('#table-weapon').dataTable({
        "bJQueryUI": true,
        "sScrollX": "",
        "bSortClasses": false,
        "aaSorting": [[0,'asc']],
        "bAutoWidth": true,
        "bInfo": true,
        "bFilter": false,
        "sScrollY": "100%",
        "sScrollX": "100%",
        "bScrollCollapse": true,
        "sPaginationType": "full_numbers",
        "bProcessing" : true,
        "bServerSide" : true,
        "sAjaxSource" : baseUrl + '/cms/ship.weaponry/dataapi',
        "fnServerData" : function(sSource, aoData, fnCallback) {
            // @optional filter category content
            jQuery.getJSON(sSource, aoData, function(json) {
                fnCallback(json);
            });
        },
		'aoColumns' : [null,null,null,null,{bSortable: false}]
    });//.makeEditable();
});
</script>