<?php 
    $this->headTitle( 'Olah Yudha | Seskoal' );
//    $this->headScript()->appendFile( $this->jsUrl( 'custom.js' ) );
?>

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">

        <!-- iPhone, iPad and Android specific settings -->
        <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1;">
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />

        <!-- Create an icon and splash screen for iPhone and iPad -->
        <!-- todo:icon + splash screen buat iphone dan ipad -->
        <link rel="apple-touch-icon" href="<?php echo $this->imgUrl( 'iOS_icon.png' ); ?>"/>
        <link rel="apple-touch-startup-image" href="<?php echo $this->imgUrl( 'iOS_startup.png' ); ?>"/>

        <link rel="shortcut icon" href="<?php echo $this->imgUrl( 'favicon.ico' ) ?>" type="image/gif" />
        <link rel="icon" href="<?php echo $this->imgUrl( 'favicon.ico' ) ?>" type="image/gif" />

        <?php echo $this->headTitle() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>

        <script type="text/javascript">
            var jsUrl = "<?php echo $this->siteUrl(); ?>";
            var imgUrl = "<?php echo $this->imgUrl(); ?>";
            var baseUrl = '<?php echo $this->baseUrl(); ?>';
            var serverUrl = "http://10.1.1.103:8080/geoserver/wms";
        </script>

<!--        --><?php //echo $this->headScript() ?>

</head>

<body>
        <?php echo $this->layout()->content ?>
</body>
</html>
